---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-prod-deployment
  labels:
    app: myapp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-prod
  template:
    metadata:
      labels:
        app: myapp-prod
    spec:
      containers:
        - name: hellos
          image: ubuntu:22.04
          command: ['sh', '-c', 'echo "Hello, Kubernetes!" >> /data/out.txt && sleep 3600']
          volumeMounts:
          - name: myapp-prod
            mountPath: "/data"
      volumes:
      - name: myapp-prod
        persistentVolumeClaim:
          claimName: myapp-prod

