---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-api-deployment
  labels:
    app: myapp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-api
  template:
    metadata:
      labels:
        app: myapp-api
    spec:
      containers:
        - name: api
          imagePullPolicy: Always
          image: wjallen/demo-app:1.0
          command: ['python3', 'api.py']
          env:
          - name: REDIS_IP
            value: 10.233.51.145
