---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-worker-deployment
  labels:
    app: myapp-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-worker
  template:
    metadata:
      labels:
        app: myapp-worker
    spec:
      containers:
        - name: worker
          imagePullPolicy: Always
          image: wjallen/demo-app:1.0
          command: ['python3', 'worker.py']
          env:
          - name: REDIS_IP
            value: 10.233.51.145

