---
apiVersion: v1
kind: Service
metadata:
    name: myapp-api-service
spec:
    type: ClusterIP
    selector:
        app: myapp-api
    ports:
    - name: myapp-api
      port: 5000
      targetPort: 5000
