---
apiVersion: v1
kind: Service
metadata:
    name: myapp-db-service
spec:
    type: ClusterIP
    selector:
        app: myapp-db
    ports:
    - name: myapp-db
      port: 6379
      targetPort: 6379
